# Generated by Django 2.0.9 on 2018-11-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Storge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Device')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='use',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.User'),
        ),
    ]
