# Generated by Django 2.0.9 on 2018-11-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storge',
            new_name='Storage',
        ),
    ]
