# Generated by Django 2.0.9 on 2018-11-06 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.User')),
            ],
        ),
    ]
